# sync_prt.ps1
# Copy light.txt / transport.txt generated by nori (prt/scenes/cubemap)
# into the web side (homework2/assets/cubemap).
# Usage: powershell -ExecutionPolicy Bypass -File sync_prt.ps1

$root   = $PSScriptRoot
$srcDir = Join-Path $root "prt\scenes\cubemap"
$dstDir = Join-Path $root "homework2\assets\cubemap"

$names = @('GraceCathedral', 'Indoor', 'Skybox')

foreach ($n in $names) {
    $src = Join-Path $srcDir $n
    $dst = Join-Path $dstDir $n

    if (-not (Test-Path $src)) {
        Write-Host "[SKIP] $n : missing in scenes (run nori for this envmap first)" -ForegroundColor Yellow
        continue
    }

    foreach ($f in @('light.txt', 'transport.txt')) {
        $s = Join-Path $src $f
        if (Test-Path $s) {
            Copy-Item $s (Join-Path $dst $f) -Force
            Write-Host "[OK] $n\$f synced" -ForegroundColor Green
        } else {
            Write-Host "[MISS] $n\$f : not found in scenes, skipped" -ForegroundColor Yellow
        }
    }
}

Write-Host "Done. Hard refresh the browser (Ctrl+Shift+R)." -ForegroundColor Cyan
